### ISSUE TITLE
eet.h error

### ISSUE THREAD

**Issue by jlslinux** [batden/elucidate#1]
Found ninja-1.10.0 at /usr/bin/ninja
ninja: Entering directory `build'
[54/61] Compiling C++ object 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o'.
FAILED: example/50d858e@@efl_animview@exe/efl_animview.cpp.o 
ccache g++ -Iexample/50d858e@@efl_animview@exe -Iexample -I../example -Iinc -I../inc -I. -I../ -I/usr/local/include/elput-1 -I/usr/local/include/ephysics-1 -I/usr/local/include/eet-1 -I/usr/include/elementary-1 -I/usr/include/ecore-x-1 -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-drm2-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/embryo-1 -I/usr/include/ecore-audio-1 -I/usr/include/bullet -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/evas-1/gesture -I/usr/include/ector-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/luajit-2.1 -I/usr/include/harfbuzz -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/emile-1 -I/usr/include/p11-kit-1 -I/usr/include/efl-1/interfaces -I/usr/include/eo-1 -I/usr/include/eina-1 -I/usr/include/efl-1 -I/usr/include/eina-1/eina -I/usr/include/x86_64-linux-gnu -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++14 -Os -g '-DDEMO_DIR="/home/jls/sources/sources/rlottie/example/resource/"' -D_REENTRANT -pthread -MD -MQ 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o' -MF 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o.d' -o 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o' -c ../example/efl_animview.cpp
In file included from ../example/efl_animview.cpp:22:
/usr/include/elementary-1/Elementary.h:60:10: fatal error: Eet.h: File o directory non esistente
   60 | #include <Eet.h>
      |          ^~~~~~~
compilation terminated.
[56/61] Compiling C++ object 'example/50d858e@@lottieviewer@exe/lottieview.cpp.o'.
ninja: build stopped: subcommand failed.
ninja: Entering directory `build'
[1/7] Compiling C++ object 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o'.
FAILED: example/50d858e@@efl_animview@exe/efl_animview.cpp.o 
ccache g++ -Iexample/50d858e@@efl_animview@exe -Iexample -I../example -Iinc -I../inc -I. -I../ -I/usr/local/include/elput-1 -I/usr/local/include/ephysics-1 -I/usr/local/include/eet-1 -I/usr/include/elementary-1 -I/usr/include/ecore-x-1 -I/usr/include/ecore-wl2-1 -I/usr/include/ecore-drm2-1 -I/usr/include/ethumb-client-1 -I/usr/include/ethumb-1 -I/usr/include/edje-1 -I/usr/include/ecore-evas-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/ecore-input-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/ecore-imf-1 -I/usr/include/embryo-1 -I/usr/include/ecore-audio-1 -I/usr/include/bullet -I/usr/include/elocation-1 -I/usr/include/emotion-1 -I/usr/include/evas-1 -I/usr/include/evas-1/canvas -I/usr/include/evas-1/gesture -I/usr/include/ector-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/luajit-2.1 -I/usr/include/harfbuzz -I/usr/include/eio-1 -I/usr/include/efreet-1 -I/usr/include/ecore-file-1 -I/usr/include/ecore-ipc-1 -I/usr/include/ecore-con-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/ecore-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/emile-1 -I/usr/include/p11-kit-1 -I/usr/include/efl-1/interfaces -I/usr/include/eo-1 -I/usr/include/eina-1 -I/usr/include/efl-1 -I/usr/include/eina-1/eina -I/usr/include/x86_64-linux-gnu -I/usr/local/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++14 -Os -g '-DDEMO_DIR="/home/jls/sources/sources/rlottie/example/resource/"' -D_REENTRANT -pthread -MD -MQ 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o' -MF 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o.d' -o 'example/50d858e@@efl_animview@exe/efl_animview.cpp.o' -c ../example/efl_animview.cpp
In file included from ../example/efl_animview.cpp:22:
/usr/include/elementary-1/Elementary.h:60:10: fatal error: Eet.h: File o directory non esistente
   60 | #include <Eet.h>
      |          ^~~~~~~
compilation terminated.

**Comment by batden** [comment]
Hello,

I just checked, everything builds fine here. No error.
Sometimes you really don't know what's going on or why...
My advice: Uninstall and reinstall e24.
